config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end


  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  scope module: :public do
    root 'homes#top'
    get "homes/about"=>'homes#about', as: 'about'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#error'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]

  end

end

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!--header-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#FFCC00;">
       <div class="container">
　　　　<nav class="navbar-brand navbar-left header-logo">
        <%= link_to image_tag("christmas_cake.png", size: "100x100"), root_path, class: "header-button btn text-light " %>
　　　　</nav>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav pull-right nav-pills">
<!--会員がログイン-->
          <% if customer_signed_in? %>
            <p>ようこそ、<%= current_customer.full_name %>さん!</p>
            <li><%= link_to 'マイページ', mypage_path %></li>
            <li><%= link_to '商品一覧', items_path %></li>
            <li><%= link_to 'カート', cart_items_path %></li>
            <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></li>

    <!--管理人がログイン-->
          <% elsif admin_signed_in? %>
            <li><%= link_to '商品一覧',  admin_items_path %></li>
            <li><%= link_to '会員一覧',  admin_customers_path %></li>
            <li><%= link_to '注文履歴一覧',  admin_orders_path %></li>
            <li><%= link_to 'ジャンル一覧',  admin_genres_path %></li>
            <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>

    <!--ログアウト中-->
      　　　<% else %>
            <li><%= link_to "About", about_path, class: "header-button btn text-light" %></li>
             <li><%= link_to '商品一覧', items_path %></li>
            <li><%= link_to '新規登録', new_customer_registration_path %></li>
            <li><%= link_to 'ログイン', new_customer_session_path %></li>
      　　　<% end %>
        </ul>

       <!-- 検索機能 -->
        <div class="input-group">
         <input type="text" class="form-control" placeholder="キーワードを入力">
         <button class="btn btn-outline-success" type="button" id="button-addon2"> 検索</button>
        </div>


       </div>
　　　</div>
     </nav>
    </header>


  　<main>
    <%= yield %>
    </main>

    <footer>
     <div class='container mt-5'>
      <div class='row'>
       <div class='mx-auto'>
        <p>ながの CAKE</p>
       </div>
      </div>
     </div>
    </footer>
  </body>
</html>